- cosmos_rl/dispatcher/status.py
- tests/launch_test_worker.py
If all rollouts arrive before the first policy. The buildmesh will not be executed for all the rollouts. This PR is to fix this issue.
> fix: make sure buildmesh to be executed for all rollout replicas

- cosmos_rl/utils/distributed.py
- tests/test_fp8.py
In some case, build_mesh thread will abort comm while is in use.
In fact, build_mesh thread needs to wait for nccl op complete first.
> fix: use lock protect nccl

- cosmos_rl/utils/parallelism_map.py
Simplify and generalize logic for splitting tensors for weight transfer. Before-hand only a few dimensions were supported. Now it supports splitting in any dimension of the tensor.
> Simplify and generalize slice_tensor_with_strategy

- tools/slurm/cosmos_rl_job_multi_node.sh
- tools/slurm/cosmos_rl_slurm_launch.py
Propagate launcher script to launch_replica.sh when launching from slurm.
> Fix: Slurm: Use launcher script on policy and rollout too

- cosmos_rl/rollout/vllm_rollout/vllm_rollout.py
- cosmos_rl/rollout/vllm_rollout/vllm_rollout_worker.py
This was missing -- even though trust_remote_code is hardcoded as True a few lines below.
> Pass trust_remote_code in call to from_pretrained

- Dockerfile
- docs/quickstart/installation.rst
Refactor dockerfile to enable EFA or not
- To build with AWS-EFA, `docker build -t cosmos_rl:latest -f Dockerfile .`
- To build without AWS-EFA, `docker build --build-arg COSMOS_RL_BUILD_MODE=no-efa -t cosmos_rl:latest -f Dockerfile .`
> chore: update dockerfile to support build with AWS efa or not

- cosmos_rl/policy/trainer/grpo_trainer.py
- cosmos_rl/policy/trainer/sft_trainer.py
Before this PR, the gradient clipping is operated at the granularity of model parts.
For each model part, we will compute the grad norms of that model part, and then clip on the parameters in the model part.
This PR computes the global grad norm among all model parts, and the use the global grad norm to clip all gradients.
The primary purpose is to match the torchtitan implementation here: https://github.com/pytorch/torchtitan/blob/main/torchtitan/train.py#L454C13-L454C66
This is also the preferred way to perform gradient clipping instead of clip different subset of parameters independently: https://www.lunartech.ai/blog/mastering-gradient-clipping-enhancing-neural-networks-for-optimal-training
This is because the overall gradient direction is preserved with the global norm.
> Compute grad norm among all model parts

- cosmos_rl/policy/model/qwen2_5_vl/parallelize.py
- cosmos_rl/policy/trainer/grpo_trainer.py
Torch compilation of visual encoder is constrained for dynamic shape input. We can enable `dynamic=True` option for torch.compile.
> fix: qwen2.5-vl torch.compile of GRPO

- cosmos_rl/policy/kernel/megatron_moe/README.md
- cosmos_rl/policy/kernel/megatron_moe/__init__.py
- cosmos_rl/policy/kernel/megatron_moe/fused_a2a.py
- cosmos_rl/policy/kernel/megatron_moe/fused_indices_converter.py
- cosmos_rl/policy/kernel/megatron_moe/moe_utils.py
- cosmos_rl/policy/kernel/megatron_moe/token_dispatcher.py
megatron_moe is forked from [megatron/core/transformer/moe](https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/core/transformer/moe) with minor modifications to remove dependencies on megatron core.
> Add DeepEP support based on megatron implementation. [Part 1]

- cosmos_rl/rollout/vllm_rollout/vllm_rollout_worker.py
This PR fixes a synchronization issue in the rollout broadcast mechanism to ensure consistency with vLLM's dummy load mode initialization.
In vLLM's dummy load mode, the `initialize_dummy_weights` function performs random initialization on all tensors in `model.state_dict()`, which includes both parameters and persistent buffers. However, our current Rollout-to-Rollout broadcast mechanism only synchronizes tensors from `model.parameters()`, leaving persistent buffers unsynchronized.
Modified the parameter iteration from:
```python
for parameter in self.get_underlying_model().parameters():
```
to:
```python
for parameter in self.get_underlying_model().state_dict().values():
```
This change ensures that all tensors in the model's state dictionary (including persistent buffers) are properly …
> Fix parameter synchronization to include persistent buffers in rollout broadcast

- cosmos_rl/policy/trainer/optm/__init__.py
Given that we might form multiple groups of the parameters in one model part, would like to add checks to ensure that the optimizers from different groups have unique keys. This is because we flattened all optimizer state_dicts in checkpoint saving/loading. So add the check to ensure it is safe to keep the parameter groups.
> Raise exception when encountering duplicated optimizer state_dict keys

- cosmos_rl/policy/trainer/sft_trainer.py
When you call `F.cross_entropy(..., ignore_index=-100)` and every target is `-100`, PyTorch ends up dividing by zero and returns NaN. You have to catch that “all-ignored” case and return something sane (e.g. zero) instead.
> fix sft loss for `all-masked` labels

- cosmos_rl/policy/trainer/sft_trainer.py
https://github.com/pytorch/pytorch/blob/134179474539648ba7dee1317959529fbd0e7f89/torch/utils/data/dataloader.py#L541
Length of a `torch.data.DataLoader` is defined in two ways. So it may lead to unexpected behavior. We can compute this on our own.
> fix sft total steps computation

- cosmos_rl/policy/config/__init__.py
Add a custom config that is parsed by the user provided script.
This allows adding custom config parameters without polluting the global configs.
Example usage: https://github.com/nvidia-cosmos/cosmos-reason1/blob/f239ad357e9e4f8fb209b1560a974a18feb893e1/tools/dataset/cosmos_sft.py#L108
Doesn't affect existing code. Manually tested using above example.
> Add custom script config

- Dockerfile
```
File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 993, in register
raise ValueError(f"'{key}' is already used by a Transformers config, pick another name.")
ValueError: 'aimv2' is already used by a Transformers config, pick another name.
raise ValueError(f"'{key}' is already used by a Transformers config, pick another name.")
ValueError: 'aimv2' is already used by a Transformers config, pick another name.
raise ValueError(f"'{key}' is already used by a Transformers config, pick another name.")
ValueErrorraise ValueError(f"'{key}' is already used by a Transformers config, pick another name.")
```
Include [fix](https://github.com/vllm-project/vllm/commit/3fc964433a84bad785d9d0656fd56195462321b8) from vllm
> Update vllm version to latest v0.10.0 to fix CI

- cosmos_rl/policy/kernel/moe/moe.py
Follow up of https://github.com/nvidia-cosmos/cosmos-rl/pull/126
moe.py is a sharable module that can benefit DSV3 and later other MoE models.
This is a naive copy to unblock other work streams from cosmos-reason1 side.
TODO:
- Change qwen_moe to use moe.py
- unifiy moe.py with `cosmos_rl/policy/kernel/moe/*`
> [DeepEP support part2] copy moe.py from cosmos-reason1 to cosmos-rl

- cosmos_rl/dispatcher/data/packer/qwen2_5_vlm_data_packer.py
- cosmos_rl/policy/trainer/grpo_trainer.py
- cosmos_rl/rollout/vllm_rollout/vllm_rollout_worker.py
- cosmos_rl/utils/distributed.py
For GRPO, we should enable `add_generation_prompt`  by default so that the concat of `prompt` and `completion` is correct. Otherwise, it may lead to in-stable training of GRPO.
> fix: qwen2.5-vl GRPO template

- cosmos_rl/dispatcher/controller.py
- cosmos_rl/dispatcher/status.py
- cosmos_rl/policy/config/__init__.py
- cosmos_rl/policy/trainer/optm/__init__.py
- cosmos_rl/rollout/vllm_rollout/vllm_rollout_worker.py
This is a feature just for `ON-POLICY` rollout verification, NOT recommended for production usage.
Add fully on-policy rollout support:
1. To enable this feature, set `config.train.train_policy.fully_on_policy = true`;
2. `config.train.weight_sync_interval` must be `1` if on-policy is forced, otherwise weight-version checking does not work;
3. If some `rollout` replicas scale down or crash, the prompt will be dropped, then the ongoing training may be stuck because there will be no enough rollout for next step anymore. In this case, we simply fallback to async mode as soon as `scaling down` event occurs;
Behavior changes:
1. We used to filter the rollout completions with length of zero, `""`. Somehow this will lead to the unexpected decrease number of rollouts/samples received by …
> feat: add fullly on-policy support for GRPO

- cosmos_rl/launcher/launch_replica.sh
We print all the envs that we set inside `launch_replica.sh`:
Output like:
```
[Cosmos-RL] POLICY Pre-setting environment variable NCCL_CUMEM_ENABLE=1
[Cosmos-RL] POLICY Pre-setting environment variable TORCH_CPP_LOG_LEVEL=ERROR
[Cosmos-RL] POLICY Pre-setting environment variable COSMOS_ROLE=Policy
[Cosmos-RL] ROLLOUT Pre-setting environment variable NCCL_CUMEM_ENABLE=1
[Cosmos-RL] ROLLOUT Pre-setting environment variable TORCH_CPP_LOG_LEVEL=ERROR
[Cosmos-RL] ROLLOUT Pre-setting environment variable COSMOS_ROLE=Rollout
```
> print env preset for users

- cosmos_rl/policy/model/gpt/__init__.py
- cosmos_rl/policy/model/qwen2_5_vl/__init__.py
- cosmos_rl/policy/model/qwen3_moe/__init__.py
- cosmos_rl/policy/trainer/grpo_trainer.py
- cosmos_rl/utils/util.py
By default, we compute all logits for GPRO including `prompt` and `completion`, while sometimes the `prompt` is pretty long, which introduces both compute and memory overhead.
While for GRPO training, `logits[:, :len(prompt) - 1]` is not needed for loss computation. So we could just drop them during logits computation.
According to my test, average memory utilization decreases by about 12-15% for `cosmos-reason1` GRPO dataset.
> optimize: GRPO logits memory

- cosmos_rl/policy/trainer/grpo_trainer.py
TP will shard the sequence dimension into n-ranks.  `interested_tokens` will be unevenly distributed across ranks. So do not enable interested_tokens in TP.
> fix: disable interested tokens for TP

- cosmos_rl/policy/lora/plugin.py
According to [Peft](https://github.com/huggingface/peft/blob/a2c6612b1268d46c8e01503bbd3d2420f03b3e1f/src/peft/tuners/lora/layer.py#L274), lora_A weights should be initialized in `kaiming` method.
> fix: use kaiming init for lora

- cosmos_rl/launcher/launch_all.py
In lepton for torch run one replica on multiple nodes, we need set hostname to make the connection work.
But sometimes the previous used `hostname` in lepton manner is too long and cannot be set.
So, we use the eth ip as the `hostname` to be set, and can work in the failed cases.
Tested:
grpo:
https://dashboard.dgxc-lepton.nvidia.com/workspace/b5k2m9x7/compute/jobs/detail/ccot-base-lightr1-debug-w97c/replicas/list
sft:
https://dashboard.dgxc-lepton.nvidia.com/workspace/b5k2m9x7/compute/jobs/detail/echo-sft-test-46z4/replicas/list
> fix: hostname setting problem for lepton case when cross node replica 

- cosmos_rl/policy/trainer/sft_trainer.py
- cosmos_rl/utils/checkpoint.py
Before this change, we need to advance the dataloader iterator until it match the last training batch/sample position. This is correct but may materialize the underlying `dataset.__getitem__`, which could be very slow for VLM models with video/image processing.
This PR mainly alleviate this by advancing the `Sampler[int]`, which will not introduce the overhead brought by dataset sample processing.
Close: https://github.com/nvidia-cosmos/cosmos-rl/issues/233
> Optimization: Quick dataloader advancing after checkpoint resumed

- configs/deepseek-v3/deepseek-v3-moe-670b-fsdp64-cp4-ep64-grpo.toml
- cosmos_rl/dispatcher/data/packer/deepseek_data_packer.py
- cosmos_rl/policy/model/deepseek_v3/__init__.py
- cosmos_rl/policy/model/deepseek_v3/grpo_launcher.py
- cosmos_rl/rollout/vllm_rollout/vllm_rollout.py
This PR upstreams the changes needed for GRPO experiments for Deepseek V3 LLM.
To run the model in CW-DFW cluster, I run the following command:
```
export CONTAINER_IMAGE_IN=/lustre/fsw/portfolios/sw/users/boryiings/images/cosmos/img4_echo_pt27_vllm_cosmos_rl.sqsh; python tools/slurm/dispatch_job.py --config-path configs/deepseek-v3/deepseek-v3-moe-670b-fsdp64-cp4-ep64-grpo.toml --output-root-path /home/heslami/lustre/logs --cosmos-container $CONTAINER_IMAGE_IN --ngpu-per-node 8 --repo-root-path $(pwd -P .) cosmos_rl/policy/model/deepseek_v3/grpo_launcher.py
```
> [3/n] Support Deepseek V3 GRPO / Deepseek R1

- cosmos_rl/dispatcher/data/packer/__init__.py
- cosmos_rl/dispatcher/data/packer/base.py
- cosmos_rl/dispatcher/run_web_panel.py
- cosmos_rl/launcher/launch_all.py
- cosmos_rl/launcher/launch_controller.sh
- cosmos_rl/launcher/launch_replica.sh
- cosmos_rl/launcher/worker_entry.py
- cosmos_rl/tools/dataset/gsm8k_grpo.py
- tests/custom_dataset/custom_gsm8k_grpo.py
- tests/test_custom_args.py
Users could pass custom arguments to customized dataset script like:
```
cosmos-rl --config ./configs/qwen2-5/qwen2-5-3b-p-fsdp1-tp1-r-tp1-pp1-grpo.toml ./tests/custom_dataset/custom_gsm8k_grpo.py --foo cosmos cosmos_rl
```
`--foo cosmos cosmos_rl` will be forwarded to the `custom_gsm8k_grpo.py` and users must handle them manually.
To achieve this, users must add customized argument to `worker_entry_parser`. Then they can do some customized things inside the entry script.
> Support of passing custom arguments to custom dataset script.

- cosmos_rl/policy/model/deepseek_v3/weight_mapper.py
- cosmos_rl/rollout/vllm_rollout/vllm_rollout.py
- cosmos_rl/utils/parallelism_map.py
Currently Deepseek V3 runs hit [this](https://github.com/nvidia-cosmos/cosmos-rl/blob/main/cosmos_rl/utils/parallelism_map.py#L101) assertion issue when running GRPO when using EP. However, for deepseek model, given the mix of dense/MoE layers, EP is not supported in rollout. In other words, rollout assumes that the tensor being constructed in the full tensor.
This PR removes `deepseek_v3` model from the list of MoE models in rollout to get around the issue.
As part of the investigation, I also noticed part of the logic in weight mapper is not used and can be removed to avoid confusion.
> [Fix] Deepseek V3 GRPO bug fix

- cosmos_rl/dispatcher/command.py
- cosmos_rl/dispatcher/controller.py
- cosmos_rl/dispatcher/status.py
- cosmos_rl/policy/config/__init__.py
- cosmos_rl/policy/trainer/grpo_trainer.py
- cosmos_rl/policy/trainer/sft_trainer.py
Considering:
- The replica number changing in dynamic scaling which makes the steps needed for one epoch varying;
- The concurrent control may be needed to save checkpoint at both step level and epoch level.
So, we don't modify the save frequency in steps as a newly calculated step interval from the epochs. We rather add a new control besides the step level to exactly match the epoch level save frequency in the controller.
Both sft and rl are supported.
`save_freq_in_epoch` in` config.train.ckpt` can be used to specify the frequency at epoch level for saving checkpoints.
> feat: Support epoch level save frequency by `save_freq_in_epoch`
